// Generated by CoffeeScript 1.7.1
(function() {
  Template.loginSection.events = {
    "click #login-buttons-password": function(e, tmpl) {
      if (e === true) {
        return alert("hi");
      } else {
        throw new Meteor.Error(e, "sectionerror");
      }
    }
  };

}).call(this);
