// Generated by CoffeeScript 1.7.1
(function() {
  share.User = (function() {
    function User(name) {
      this.name = name;
      this.password = "password";
    }

    return User;

  })();

}).call(this);
