// Generated by CoffeeScript 1.7.1
(function() {
  var mypackage;

  mypackage = (function() {
    function mypackage() {}

    return mypackage;

  })();

  console.log("hello-world");

  mypackage.greet = function(name) {
    return console.log("Hi. I'm " + name);
  };

  mypackage.greet("SERVER");

  mypackage.greet("CLIENT");

}).call(this);
