// Generated by CoffeeScript 1.7.1
(function() {
  var mySuite;

  mySuite = (function() {
    function mySuite() {}

    mySuite.prototype.name = "mytests";

    mySuite.prototype.testExample = function(test) {
      return test.isTrue(true);
    };

    return mySuite;

  })();

  Munit.run(new mySuite());

}).call(this);
